### ISSUE TITLE
Check for other cases besides from 1000 to 0

### ISSUE THREAD

**Issue by ThisIsHermanCheng** [grzegorz-p-adamski/encoder_watcher#1]
The encoder not always jump to 0. more likely it would jump to any value.
For example it might jump to 1:
![image](https://user-images.githubusercontent.com/45646023/231041814-1304d933-d569-4f54-8de8-38664b631062.png)

**Comment by grzegorz-p-adamski** [comment]
ok, my proposition is to check if
`abs(last_encoder_value-encoder value)>triggerValue`
or sth similar, and regarding issue #2 set `triggerValue` differently for different motors.
