### ISSUE TITLE
Check for other motors also

### ISSUE THREAD

**Issue by ThisIsHermanCheng** [grzegorz-p-adamski/encoder_watcher#2]
Seems like not only the leg motor having the problem, but also other motors.
![image](https://user-images.githubusercontent.com/45646023/231042343-4616c8c3-ce71-4019-ae07-70fd3357363f.png)

It would be great to monitor other motors also.

**Comment by grzegorz-p-adamski** [comment]
added a branch [multi](https://github.com/grzegorz-p-adamski/encoder_watcher/tree/multi) for developing the version that solves this issue
